services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami_gh
    restart: unless-stopped
    networks:
      - traefik
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # Define the route rule
      - "traefik.http.routers.whoami.rule=Host(`test.oberhofer.work`)"
      # Specify the port the service runs on
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
        
networks:
  traefik:
    external: true
  backend:
    internal: true
